cores                    = "2"
mem                      = "1"
fraction                 = "5"
instance_count           = "1"
subnet                   = "192.168.111.0/24"
instance_type            = "standard-v2"
