    - name: Create Iptables NAT chain
      iptables:
       table: nat
       chain: POSTROUTING
       out_interface: 'eth0'
       jump: MASQUERADE

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: True

    - name: Install IPtables-persistent
      apt: name=iptables-persistent state=present